---
title: "Quality Assessment of Statistical Matches: Levy Institute Measure of Time and Income Poverty (LIMTIP) for the United States"
format:
  simart-pdf:  
    keep-tex: true  
    fontsize: 11pt
author:
    - name: "Fernando Rios-Avila"
      affiliations:
        - name: "Levy Economics Institute of Bard College"
          address: Annandale-on-Hudson, NY 12504
    - name: "Aashima Sinha"
      affiliations:
        - name: "Levy Economics Institute of Bard College"
          address: Annandale-on-Hudson, NY 12504
date: "\today"
abstract: |
    In this paper we present the match quality assessment of the statistically matched data used to construct the LIMTIP estimates for the United States, specifically for those for 2022. Using a statistical matching procedure, we construct a synthetic dataset by combining the American Time-Use Survey (ATUS) 2021 with Annual Social and Economic Supplement (ASEC) 2022. First, we examine the alignment of the ATUS (weekday and weekend) and both datasets across important demographic characteristics. Next, we briefly describe results from the matching algorithm. We conclude by comparing the marginal distributions of time use between the ATUS and the synthetic dataset. Our results suggest
    that our statistical matching procedure yielded a high quality of match and the constructed synthetic dataset is appropriate for time poverty analysis. While not presented here, similar assesments were constructed for the ASEC matching from 2005 to 2021.
bibliography: biblio.bib
---

# Introduction

In this paper, we describe the construction of synthetic dataset created for use in estimation of the Levy Institute Measure of Time and Income Poverty (LIMTIP) for United States. The LIMTIP presents a comprehensive understanding of households’ poverty status by measuring a unique estimates of time and income poverty combined.  Construction of LIMTIP estimates requires a variety of information at the household and individual level. In addition to demographic characteristics, the estimation process requires information about income and time use. However, no single datset has access to comprehensive information of this type for all household members across time. To produce LIMTIP estimates, we first construct a synthetic data file by employing a statistical matching procedure to match two source datasets: the base or recipient data (ASEC), contains detailed demographic and income/consumption data for households and individuals; and the donor data (ATUS) contains individuals’ time allocation in a range of daily activities including paid work, unpaid care, domestic chores, leisure, self-care, and socializing. Using variables that are common to both datasets we use statistical matching to create a unique synthetic dataset that combines information from both sources. Using this dataset, we can extract patterns of time use and income/consumption for all household members. This in turn is useful to study gender differences in sharing of household production among other activities.

# Data Description

The construction of the US LIMTIP estimates is based on two different datasets. First, the Annual Social and Economic Supplement (ASEC) of the Current Population Survey (CPS), which provides individual and household level data on income, demographics, and employment. Second, the American Time Use Survey (ATUS), that provides time use data, from which we can estimate the amount of time households dedicate to household production including childcare, elderly care and domestic chores on a single day. A summary of the main characteristics of the data can be found in @tbl-t1. Both datasets were accessed through the Integrated Public Use Microdata Series (IPUMS) database [@ipums2022].


::: {#tbl-t1}

| Survey | Survey Subject | Source | Sample Size | Year |
| --- | --- | --- | --- | --- |
| Americal Time Use Survey | Time-Use | U.S. Census Bureau/ IPUMS | 8,136 Individuals | 2021 |
|-----|-----|-----|-----|-----|-----|
| Annual Social and Economic Supplement (CPS-ASEC) | Income, Demographics, Employment | U.S. Census Bureau/IPUMS | Full Sample: XXXX <br> Restricted Sample: 118,990 | 2022 |

Data description

:::


## Annual Social and Economic Supplement (ASEC) of the Current Population Survey (CPS)

The CPS is a monthly survey administered by the US Bureau of Labor Statistics. The survey collects comprehensive data on labor market situation including statistics related to employment and unemployment, the survey also collects detailed information on demographic characteristics (age, sex, race, and marital status), educational attainment, and family structure. Each household in the CPS is interviewed for four consecutive months, not interviewed for eight, and interviewed again for four additional months. 

In March of every year, the previously interviewed households answer additional questions, part of the ASEC supplement formerly known as the Annual Demographic File. In addition to the basic monthly information, this supplement provides additional data on work experience, income, noncash benefits, and migration. In 2014, the ASEC supplement went through a redesign of the income-collection questions. As described in @SemegaandWelniak2013, for the ASEC 2014, of the nearly 98,000 addresses in the sample, approximately one-third of the sample was randomly assigned to be eligible to receive the redesigned income questions. The remaining sample (approximately two-thirds) was eligible to receive the set of ASEC income questions used in previous years, referred to as the "traditional income questions." For the statistical matching purposes, we use the second subsample.

While we implement the statistical matching procedure for the ASEC from 2005 to 2022, the present document only describes the results for the ASEC 2022 match. The ASEC 2022 is used as the base dataset (recipient), as it contains rich information regarding demographics and economic status, for every member of the household. For the matching process, we consider data for the household, rather than family, as the aggregated level that some demographics are constructed on. The matching, however, is done at the individual level, considering only individuals who are directly or indirectly related to the household head. This implies that nonrelatives living in the household are generally not considered in the matching process. Similarly, people not living in households, such as those living in institutions or group quarters, are not considered in the matching process either.

## American Time Use Survey (ATUS)

The ATUS is a survey sponsored by the Bureau of Labor Statistics and collected by the US Census Bureau. It is the first continuous survey on time use in the United States available since 2003. Its main objective is to provide nationally representative estimates of peoples’ allocation of time among different activities, collecting information on what they did, where they were, and with whom they were over the course of a single day.  

The ATUS is administered to a random sample of individuals selected from a set of eligible households that have completed their final month’s interviews for the CPS. Only one individual per household is selected to participate in the ATUS. This individual is at least 15 years old and is part of the civilian, noninstitutionalized population in the United States. To be able to obtain a representative picture of time use across one year, data collection is spread over the entire year, and individuals are requested to report data for either a weekday or a weekend day, but not both. 

The ATUS 2021, which contains a total of **xx** observations, is used as the donor dataset to obtain information regarding time use, which will be transferred to the ASEC 2022.


# Methodology


In order to create synthetic datasets that combine data from the different sources into a single dataset, we employ a methododology known as statistical matching.

The basic Statistical matching setup consists of having access to two sources of data: survey A and survey B, which collect information from two independent samples of the same population. Survey A collects information $Z, X$, whereas survey B collects information $Z, Y$. Although both surveys collect common information $Z$ (for example demographics), they each contain information on variables that are not observed jointly: $X$ (Consumption) and $Y$ (Time use). In this case, the goal of Statistical matching is to create synthetic data that will contain all information $Y,X, Z$, linking observations across the datasets based on how close they are based on observed characteristics. It is also possible to constrain matches based on the weighted population each survey represents.

In turn, this synthetic dataset should allow researchers to analyze otherwise unobservable relationships between, $X$ and $Y$, or as in our case, income and time use [ @rassler2002; @dorazio2006]. Thus, inference on the relation between $X$ and $Y$ can only be done to the extent that $Z$ explains most of the common variation between $X$ and $Y$.

## Matching Algorithm

As described in @lewaa2021, statistical matching could be considered as a non-parametric variation of the stochastic regression approach, where no specific distribution assumption is imposed, and the imputed values are drawn directly from the observed distribution in the donor file. In particular, we implement a variation of the rank-constrained statistical matching described in @kum_masterson2010, which improves on the approach by using a weight splitting approach in combination with clustering analysis for an automatic selection of strata groups in the approach.^[ This is in contrast with previous iterations of Statistical matching used for the estimation of the LIMEW, which was based on ex-ante ad-hoc stratification, last-match-unit approach]

The statistical matching procedure applied for the paper is a multi-step process that can be explained as follows:

### Step 1: Data harmonization

The first step involves harmonizing all common variables that will be used in the matching process and survey balancing. This is a necessary step in all imputation methods because variables need to have consistent definitions before they can be utilized for imputation.

Furthermore, this step includes adjusting sample weights to ensure that the weighted population is the same across all surveys. The standard practice is to adjust the sample weights of the donor sample. Additionally, for technical reasons, the weights are adjusted to be whole numbers. While it is customary to adjust weights to match the total population, it may also be advisable to adjust weights to align with subpopulations based on selected strata variables.

Lastly, it is recommended to verify if both the donor and recipient files truly represent the same population by comparing the means, variances, and proportions of key variables across both surveys. In instances where significant imbalances are observed, reweighted methods can be employed to improve the balance between the surveys. However, there is no definitive rule to determine when a discrepancy in the distribution constitutes a substantial imbalance.

For the case of the LIMTIP, the ATUS sample weights are adjusted to match the population of 15 years or older individuals in the ASEC based on the individual `ASECWT`, excluding those not living in households, and those not related to the head of the household. To improve on the quality of the imputed data, we consider separete the ATUS sample into two groups: one from weekdays and one from weekend days. This is done to account for the different patterns of time use that are observed. Thus, weights are adjusted for each group separately. Weights are also adjusted based on three strata variables: gender of the respondant, if there is a child (<=17 years of age) in the household, and if the respondant declares to be working. 

### Step 2: Strata and Cluster identification, and propensity score estimation

The second step involves identifying statistically similar records based on ***common*** observed characteristics. This is accomplished through a combination of three methodologies:

-   **Principal Component Analysis (PCA)**: PCA is utilized as a data reduction technique to decrease the dimensionality of the ***common*** variables to a few linear combinations. While there are numerous suggestions on determining the optimal number of components, we simply select the first few components that explain approximately 50% of the data's variation.
    For the construction of the LIMTIP, we consider variables related to household struture, number of children of different ages and adults of different age groups and gender in the household, employment status of the household head and spouse (if present), level of household income, house ownership. We also consider individual demographic characteristics such as age, gender, race and education level.

-   **Cluster analysis**: Once the principal components are estimated, they are employed to identify clusters within the dataset using a k-means cluster iterative partition algorithm. A brief description of the algorithm can be found in @james_2021.

    As this algorithm only discovers locally optimal clusters and their identification is influenced by random initial conditions, it has a tendency to generate suboptimal clusters. To mitigate this issue, we modify the algorithm by repeating the procedure a sufficient number of times and selecting the "optimal" cluster based on the largest Calinski-Harabasz pseudo-F index [@calinski1974]. This ensures that the chosen cluster maximizes intra-cluster similarity while minimizing inter-cluster dissimilarity.

    This procedure generates various sets of clusters of different sizes. The clusters with the highest number of groups are prioritized in the statistical matching procedure since they represent the most similar records, while clusters with fewer groups are utilized in later stages of the matching process.

-   **Propensity score matching:** To enhance the matching procedure, we estimate a propensity score using a logit model. The dependent variable in the model is a binary indicator that determines whether an observation belongs to the donor or recipient file, while the independent variables consist of all common variables Z (including interactions or transformations). In the scenario where both surveys can be considered random samples from the same population, the expected coefficients for all variables should be zero or statistically insignificant. However, due to sampling variability and variations in survey design, it is common to observe variation in the propensity score. The logit model and propensity score can be estimated for the entire pooled survey or using the primary strata variables.

### Step 3: Matching and weight splitting.

Once the propensity score has been estimated and the clusters and strata have been defined, we proceed with our matching algorithm. We start by creating cells, which combine the identifed strata and clusters from the previous step. The cells that combine the most detailed strata and clusters will be used first, as they would identify the most similar records. In addition to the Strata and clusters, this step may also consider using other variables that are not part of the main strata, but that are important reinforcing the similarity of the records during the matching process.

Starting with the most detailed sets of cells, records within each cell are ranked in increasing order using the propensity score. Within each cell, a record with the lowest propensity score from the donor file is matched or linked to a record with the lowest propensity score in the recipient file. If both records have the same weight, they are considered as fully matched and removed from the donor or recipient pool. If the weights are different, the record (donor or recipient) with the lowest weight is removed from the pool, and the weight of the matched record is adjusted by subtracting the weight value of the excluded record. The record with the adjusted weight is retained in the pool for a subsequent match.

This process of matching records and adjusting weights, if necessary, continues until there are no more donor or recipient records left in that cell. If there are unmatched records from the previous steps, the procedure is repeated using a less detailed cluster until all records from the donor and recipient files are matched. Once the matching is completed, we obtain a synthetic dataset where all records in the donor file are matched to potentially multiple records in the recipient files, and vice versa. Records matched at an earlier stage are considered to be the best matches, while those matched at later stages are considered to be less similar.

For the final synthetic dataset, we select the "best" matched records for all the donor and recipient files. In general, records that were matched in the earlier stages (most detailed clusters) are considered to be better than those at later stages. In case of ties, records matched with the largest split weight are prefered. If further ties exist, the "best" match is randomly chosen.

Due to this step, some observations in the donor sample may not be used at all, while others may be used more frequently than their weight would suggest. However, if the sample sizes and weight structures across both files are similar, we can expect only minor discrepancies between the distribution of the imputed data in the donor and recipient datasets. Nevertheless, if the sample sizes differ significantly, it is advisable to use the largest file as the recipient file, which is our approach in the LIMTIP construction.

The statistical matching procedure described above aims to impute all missing values in the recipient file by transferring the observed distribution of the imputed values from the donor file. This transfer of information is achieved by linking records from the donor file to records in the recipient files that have similar characteristics or similar ranks, based on an index known as the propensity score, which summarizes all those characteristics. Its main advantage over other methodologies is that constrained statistical matching fully recovers the distribution of the donor sample in the imputed sample, except for minor discrepancies as explained earlier.

# Data Alignment 

In this section, we present the alignment of the ATUS (weekday and weekend) and the ASEC 2022 datasets across important demographic characteristics. The alignment is done to ensure that the two datasets are comparable and that the matching procedure is appropriate. 

** Need to create tables by Gender and all other break downs Genrder based
** On each one do ASEC ATUS Day Atus ATUS Weekend Plust Difference

# Matching Procedure

Briely describe the Matching and the table for matching (Rounds, number of matches, etc)

# Matching Quality Assessment

Here we present the results for Matching Quality

# Conclusions

This paper presents the quality assessment of the statistical matching procedure used to combine the household survey data and time use data for the United States to obtain comprehensive estimates on time and income poverty. 
Overall, the two datasets are well aligned, which warrants the implementation of the statistical matching. Based on the statistics presented here, the matching quality is good, showing strong balance across different household characteristics. There are, however, a few large imbalances that are isolated in small groups. Overall, we conclude that the statistical matching procedure employed has precisely imputed time-use estimates for the household survey, which in turn contributed towards producing an insightful measure of poverty for the US-LIMTIP. 


# References {.unnumbered}

::: {#refs}
:::